# Generated by Django 4.2.17 on 2025-02-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Number', models.CharField(max_length=10)),
                ('College_name', models.CharField(max_length=50)),
                ('Event_name', models.CharField(max_length=20)),
            ],
        ),
    ]
