# Generated by Django 4.2.17 on 2025-02-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
