# Generated by Django 4.2.17 on 2025-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter your name', max_length=20)),
                ('register_no', models.IntegerField(max_length=20)),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=20)),
                ('collage', models.CharField(help_text='Enter your collage name', max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
