# Generated by Django 4.2.17 on 2025-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_no',
            field=models.IntegerField(help_text='Enter your register number'),
        ),
    ]
