# Generated by Django 4.2.17 on 2025-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_rename_id_student_id_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='collage',
            field=models.CharField(help_text='Enter your college name', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_no',
            field=models.IntegerField(help_text='Enter your register number', unique=True),
        ),
    ]
