# Generated by Django 4.2.17 on 2025-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_student_delete_studentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='collage',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
