# Generated by Django 4.2.17 on 2025-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cultural',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Clg_Name', models.CharField(max_length=50)),
                ('Clg_Address', models.CharField(max_length=100)),
                ('Event_Name', models.CharField(max_length=200)),
                ('Date', models.DateField(blank=True, null=True)),
                ('cultural_Poster', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('Number', models.CharField(max_length=10, unique=True)),
                ('College_name', models.CharField(max_length=50)),
                ('Event_name', models.CharField(max_length=20)),
            ],
        ),
    ]
