# Generated by Django 4.2.17 on 2025-02-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_register_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='register',
        ),
    ]
