# Generated by Django 5.1.4 on 2025-01-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clg_Name', models.CharField(max_length=50)),
                ('Clg_Address', models.CharField(max_length=100)),
                ('Event_Name', models.CharField(max_length=200)),
                ('Date', models.IntegerField()),
            ],
        ),
    ]
