# Generated by Django 4.2.17 on 2025-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
