# Generated by Django 4.2.17 on 2025-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_cultural_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural',
            name='Date',
            field=models.IntegerField(),
        ),
    ]
