# Generated by Django 4.2.17 on 2025-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_cultural_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural',
            name='cultural_Poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
