# Generated by Django 4.2.17 on 2025-01-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_cultural_cultural_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
